import packageJson from '../../package.json';
import i18n from '../i18n';
import { StateCleanerObject, StateObject } from "./types";

export const currentVersion = packageJson.version;

const word = i18n.t("Word", { ns: "lexicon" });
const partOfSpeech = i18n.t("PartOfSpeech", { ns: "lexicon" });
const definition = i18n.t("Definition", { ns: "lexicon" });

const blankAppState: StateObject = {
	ms: {
		id: "",
		lastSave: 0,
		title: "",
		description: "",

		BOOL_prefixMost: false,
		BOOL_prefixLess: false,
		BOOL_suffixMost: false,
		BOOL_suffixLess: false,
		BOOL_circumfixMost: false,
		BOOL_circumfixLess: false,
		BOOL_infixMost: false,
		BOOL_infixLess: false,
		BOOL_actions: false,
		BOOL_actionProcesses: false,
		BOOL_weather: false,
		BOOL_states: false,
		BOOL_involuntaryProcesses: false,
		BOOL_bodyFunctions: false,
		BOOL_motion: false,
		BOOL_position: false,
		BOOL_factive: false,
		BOOL_cognition: false,
		BOOL_sensation: false,
		BOOL_emotion: false,
		BOOL_utterance: false,
		BOOL_manipulation: false,
		BOOL_otherVerbClass: false,
		BOOL_lexVerb: false,
		BOOL_lexNoun: false,
		BOOL_lexVN: false,
		BOOL_lexVorN: false,
		BOOL_adjectives: false,
		BOOL_baseFive: false,
		BOOL_baseTen: false,
		BOOL_baseTwenty: false,
		BOOL_baseOther: false,
		BOOL_numGL: false,
		BOOL_numLG: false,
		BOOL_numNone: false,
		BOOL_multiNumSets: false,
		BOOL_inflectNum: false,
		BOOL_APV: false,
		BOOL_AVP: false,
		BOOL_VAP: false,
		BOOL_VPA: false,
		BOOL_PAV: false,
		BOOL_PVA: false,
		BOOL_preP: false,
		BOOL_postP: false,
		BOOL_circumP: false,
		BOOL_numSing: false,
		BOOL_numDual: false,
		BOOL_numTrial: false,
		BOOL_numPaucal: false,
		BOOL_numPlural: false,
		BOOL_classGen: false,
		BOOL_classAnim: false,
		BOOL_classShape: false,
		BOOL_classFunction: false,
		BOOL_classOther: false,
		BOOL_dimAugYes: false,
		BOOL_dimAugObligatory: false,
		BOOL_dimAugProductive: false,
		BOOL_nomAcc: false,
		BOOL_ergAbs: false,
		BOOL_markInv: false,
		BOOL_markDirInv: false,
		BOOL_verbAgreeInv: false,
		BOOL_wordOrderChange: false,
		BOOL_tenseMorph: false,
		BOOL_aspectMorph: false,
		BOOL_modeMorph: false,
		BOOL_otherMorph: false,
		BOOL_chainFirst: false,
		BOOL_chainLast: false,
		BOOL_chainN: false,
		BOOL_chainV: false,
		BOOL_chainCj: false,
		BOOL_chainT: false,
		BOOL_chainA: false,
		BOOL_chainPer: false,
		BOOL_chainNum: false,
		BOOL_chainOther: false,
		BOOL_relPre: false,
		BOOL_relPost: false,
		BOOL_relInternal: false,
		BOOL_relHeadless: false,
		BOOL_coordMid: false,
		BOOL_coordTwo: false,
		BOOL_coordLast: false,

		NUM_synthesis: 0,
		NUM_fusion: 0,
		NUM_stemMod: 0,
		NUM_suppletion: 0,
		NUM_redupe: 0,
		NUM_supraMod: 0,
		NUM_headDepMarked: 0,

		TEXT_tradTypol: "",
		TEXT_morphProcess: "",
		TEXT_headDepMark: "",
		TEXT_propNames: "",
		TEXT_possessable: "",
		TEXT_countMass: "",
		TEXT_pronounAnaphClitic: "",
		TEXT_semanticRole: "",
		TEXT_verbClass: "",
		TEXT_verbStructure: "",
		TEXT_propClass: "",
		TEXT_quantifier: "",
		TEXT_numeral: "",
		TEXT_adverb: "",
		TEXT_mainClause: "",
		TEXT_verbPhrase: "",
		TEXT_nounPhrase: "",
		TEXT_adPhrase: "",
		TEXT_compare: "",
		TEXT_questions: "",
		TEXT_COType: "",
		TEXT_compounding: "",
		TEXT_denoms: "",
		TEXT_nNumberOpt: "",
		TEXT_nNumberObl: "",
		TEXT_nCase: "",
		TEXT_articles: "",
		TEXT_demonstratives: "",
		TEXT_possessors: "",
		TEXT_classGender: "",
		TEXT_dimAug: "",
		TEXT_predNom: "",
		TEXT_predLoc: "",
		TEXT_predEx: "",
		TEXT_ergative: "",
		TEXT_causation: "",
		TEXT_applicatives: "",
		TEXT_dativeShifts: "",
		TEXT_datOfInt: "",
		TEXT_possessRaising: "",
		TEXT_refls: "",
		TEXT_recips: "",
		TEXT_passives: "",
		TEXT_inverses: "",
		TEXT_middleCon: "",
		TEXT_antiP: "",
		TEXT_objDemOmInc: "",
		TEXT_verbNoms: "",
		TEXT_verbComp: "",
		TEXT_tense: "",
		TEXT_aspect: "",
		TEXT_mode: "",
		TEXT_locDirect: "",
		TEXT_evidence: "",
		TEXT_miscVerbFunc: "",
		TEXT_pragFocusEtc: "",
		TEXT_negation: "",
		TEXT_declaratives: "",
		TEXT_YNQs: "",
		TEXT_QWQs: "",
		TEXT_imperatives: "",
		TEXT_serialVerbs: "",
		TEXT_complClauses: "",
		TEXT_advClauses: "",
		TEXT_clauseChainEtc: "",
		TEXT_relClauses: "",
		TEXT_coords: ""
	},
	wg: {
		// GROUPS
		characterGroups: [],
		// SYLLABLES
		multipleSyllableTypes: false,
		singleWord: "",
		wordInitial: "",
		wordMiddle: "",
		wordFinal: "",
		syllableDropoffOverrides: {
			singleWord: null,
			wordInitial: null,
			wordMiddle: null,
			wordFinal: null
		},
		// TRANSFORMS
		transforms: [],
		// SETTINGS
		//...simple.wordgenSettings,
		monosyllablesRate: 20,
		maxSyllablesPerWord: 6,
		characterGroupDropoff: 25,
		syllableBoxDropoff: 20,
		capitalizeSentences: true,
		declarativeSentencePre: "",
		declarativeSentencePost: ".",
		interrogativeSentencePre: "",
		interrogativeSentencePost: "?",
		exclamatorySentencePre: "",
		exclamatorySentencePost: "!",
		customSort: null,
		//...end simple.wordgenSettings
		output: "text",
		showSyllableBreaks: false,
		sentencesPerText: 30,
		capitalizeWords: false,
		sortWordlist: true,
		wordlistMultiColumn: true,
		wordsPerWordlist: 250
	},
	we: {
		input: "",
		characterGroups: [],
		transforms: [],
		soundChanges: [],
		outputStyle: "outputOnly",
		inputLower: false,
		inputAlpha: true,
		customSort: null
	},
	dj: {
		input: "",
		declensions: [],
		conjugations: [],
		other: []
	},
	lexicon: {
		id: "",
		lastSave: 0,
		title: "",
		description: "",
		truncateColumns: true,
		sortDir: false,
		sortPattern: [0, 1, 2],
		columns: [
			{
				id: "00",
				label: word,
				size: "m"
			},
			{
				id: "11",
				label: partOfSpeech,
				size: "s"
			},
			{
				id: "22",
				label: definition,
				size: "l"
			}
		],
		lexicon: [],
		blankSort: "alphaFirst",
		fontType: "Noto Serif",
		customSort: undefined
	},
	concepts: {
		textCenter: true,
		display: {},
		showingCombos: false,
		combinations: []
	},
	ec: {
		faves: [],
		copyImmediately: false,
		toCopy: "",
		showNames: false,
		nowShowing: "Favorites"
	},
	appSettings: {
		theme: 'Default',
		disableConfirms: false
	},
	sortSettings: {
		sensitivity: "variant",
		customSorts: []
	},
	internals: {
		defaultSortLanguage: "unicode",
		logs: [],
		lastClean: 0,
		lastViewMS: "msSettings"
	}
};

export default blankAppState;

export const cleanerObject: StateCleanerObject = {
	wg: [
		"monosyllablesRate",
		"maxSyllablesPerWord",
		"characterGroupDropoff",
		"syllableBoxDropoff",
		"capitalizeSentences",
		"declarativeSentencePre",
		"declarativeSentencePost",
		"interrogativeSentencePre",
		"interrogativeSentencePost",
		"exclamatorySentencePre",
		"exclamatorySentencePost",
		"customSort",
		"characterGroups",
		"multipleSyllableTypes",
		"singleWord",
		"wordInitial",
		"wordMiddle",
		"wordFinal",
		"syllableDropoffOverrides",
		"transforms",
		"output",
		"showSyllableBreaks",
		"sentencesPerText",
		"capitalizeWords",
		"sortWordlist",
		"wordlistMultiColumn",
		"wordsPerWordlist"
	],
	we: [
		"characterGroups",
		"soundChanges",
		"transforms",
		"input",
		"outputStyle",
		"inputLower",
		"inputAlpha",
		"customSort"
	],
	ms: [
		"id",
		"lastSave",
		"title",
		"description"
	],
	msBool: [
		"BOOL_prefixMost",
		"BOOL_prefixLess",
		"BOOL_suffixMost",
		"BOOL_suffixLess",
		"BOOL_circumfixMost",
		"BOOL_circumfixLess",
		"BOOL_infixMost",
		"BOOL_infixLess",
		"BOOL_actions",
		"BOOL_actionProcesses",
		"BOOL_weather",
		"BOOL_states",
		"BOOL_involuntaryProcesses",
		"BOOL_bodyFunctions",
		"BOOL_motion",
		"BOOL_position",
		"BOOL_factive",
		"BOOL_cognition",
		"BOOL_sensation",
		"BOOL_emotion",
		"BOOL_utterance",
		"BOOL_manipulation",
		"BOOL_otherVerbClass",
		"BOOL_lexVerb",
		"BOOL_lexNoun",
		"BOOL_lexVN",
		"BOOL_lexVorN",
		"BOOL_adjectives",
		"BOOL_baseFive",
		"BOOL_baseTen",
		"BOOL_baseTwenty",
		"BOOL_baseOther",
		"BOOL_numGL",
		"BOOL_numLG",
		"BOOL_numNone",
		"BOOL_multiNumSets",
		"BOOL_inflectNum",
		"BOOL_APV",
		"BOOL_AVP",
		"BOOL_VAP",
		"BOOL_VPA",
		"BOOL_PAV",
		"BOOL_PVA",
		"BOOL_preP",
		"BOOL_postP",
		"BOOL_circumP",
		"BOOL_numSing",
		"BOOL_numDual",
		"BOOL_numTrial",
		"BOOL_numPaucal",
		"BOOL_numPlural",
		"BOOL_classGen",
		"BOOL_classAnim",
		"BOOL_classShape",
		"BOOL_classFunction",
		"BOOL_classOther",
		"BOOL_dimAugYes",
		"BOOL_dimAugObligatory",
		"BOOL_dimAugProductive",
		"BOOL_nomAcc",
		"BOOL_ergAbs",
		"BOOL_markInv",
		"BOOL_markDirInv",
		"BOOL_verbAgreeInv",
		"BOOL_wordOrderChange",
		"BOOL_tenseMorph",
		"BOOL_aspectMorph",
		"BOOL_modeMorph",
		"BOOL_otherMorph",
		"BOOL_chainFirst",
		"BOOL_chainLast",
		"BOOL_chainN",
		"BOOL_chainV",
		"BOOL_chainCj",
		"BOOL_chainT",
		"BOOL_chainA",
		"BOOL_chainPer",
		"BOOL_chainNum",
		"BOOL_chainOther",
		"BOOL_relPre",
		"BOOL_relPost",
		"BOOL_relInternal",
		"BOOL_relHeadless",
		"BOOL_coordMid",
		"BOOL_coordTwo",
		"BOOL_coordLast"
	],
	msNum: [
		"NUM_synthesis",
		"NUM_fusion",
		"NUM_stemMod",
		"NUM_suppletion",
		"NUM_redupe",
		"NUM_supraMod",
		"NUM_headDepMarked"
	],
	msText: [
		"TEXT_tradTypol",
		"TEXT_morphProcess",
		"TEXT_headDepMark",
		"TEXT_propNames",
		"TEXT_possessable",
		"TEXT_countMass",
		"TEXT_pronounAnaphClitic",
		"TEXT_semanticRole",
		"TEXT_verbClass",
		"TEXT_verbStructure",
		"TEXT_propClass",
		"TEXT_quantifier",
		"TEXT_numeral",
		"TEXT_adverb",
		"TEXT_mainClause",
		"TEXT_verbPhrase",
		"TEXT_nounPhrase",
		"TEXT_adPhrase",
		"TEXT_compare",
		"TEXT_questions",
		"TEXT_COType",
		"TEXT_compounding",
		"TEXT_denoms",
		"TEXT_nNumberOpt",
		"TEXT_nNumberObl",
		"TEXT_nCase",
		"TEXT_articles",
		"TEXT_demonstratives",
		"TEXT_possessors",
		"TEXT_classGender",
		"TEXT_dimAug",
		"TEXT_predNom",
		"TEXT_predLoc",
		"TEXT_predEx",
		"TEXT_predPoss",
		"TEXT_ergative",
		"TEXT_causation",
		"TEXT_applicatives",
		"TEXT_dativeShifts",
		"TEXT_datOfInt",
		"TEXT_possessRaising",
		"TEXT_refls",
		"TEXT_recips",
		"TEXT_passives",
		"TEXT_inverses",
		"TEXT_middleCon",
		"TEXT_antiP",
		"TEXT_objDemOmInc",
		"TEXT_verbNoms",
		"TEXT_verbComp",
		"TEXT_tense",
		"TEXT_aspect",
		"TEXT_mode",
		"TEXT_locDirect",
		"TEXT_evidence",
		"TEXT_miscVerbFunc",
		"TEXT_pragFocusEtc",
		"TEXT_negation",
		"TEXT_declaratives",
		"TEXT_YNQs",
		"TEXT_QWQs",
		"TEXT_imperatives",
		"TEXT_serialVerbs",
		"TEXT_complClauses",
		"TEXT_advClauses",
		"TEXT_clauseChainEtc",
		"TEXT_relClauses",
		"TEXT_coords"
	],
	dj: [
		"declensions",
		"conjugations",
		"other",
		"input"
	],
	lexicon: [
		"id",
		"lastSave",
		"title",
		"description",
		"columns",
		"truncateColumns",
		"lexicon",
		"sortDir",
		"sortPattern",
		"blankSort",
		"fontType",
		"customSort"
	],
	concepts: [
		"display",
		"textCenter",
		"showingCombos",
		"combinations"
	],
	ec: [
		"faves",
		"toCopy",
		"copyImmediately",
		"showNames",
		"nowShowing"
	],
	appSettings: [
		"theme",
		"disableConfirms"
	],
	sortSettings: [
		"customSorts",
		"sortLanguage",
		"sensitivity",
		"defaultCustomSort"
	]
};
